### ISSUE TITLE
Figyeljoda.js

### ISSUE THREAD

**Issue by Tasztalos69** [nimfasFTW/BBB#2]
Kösz srácok, banyúltuk 😋 
Legközelebb legyen privát a repo, jobban jártok 🤣 
Jó versenyzést 😀

**Comment by btoth04** [comment]
A kolléga csak viccel, ő is ugyanazt a jótanácsot kívánta elmondani mint én. A verseny közben legyen privát, mert egy kevésbé jóindulatú csapat tényleg lenyúlhatja. Max ha vége, akkor osszátok meg.

**Comment by Tasztalos69** [comment]
Így van srácok, legközelebb figyeljetek oda erre. 😉
